-- Import Keto Recipes from CSV
-- Create a default "System" user first if it doesn't exist
INSERT OR IGNORE INTO "User" ("id") VALUES (1);

-- Insert recipes as system recipes that can be shared
INSERT INTO "Recipe" ("name", "type", "ingredients", "instructions", "isFavorite", "userId") VALUES
('AVOCADO BREAKFAST BOWL', 'Breakfast', '1 AVOCADO, HALVED AND THE STONE REMOVED; 1 TBSP SALTED BUTTER; 3 LARGE FREE RANGE EGGS; 3 RASHERS OF BACON, CUT INTO SMALL PIECES; PINCH OF SALT; PINCH OF BLACK PEPPER', '1. Start off by scooping out most of the avocado flesh, leaving about 1/2 inch around the avocado. 2. Place a large saucepan on a low heat and add in the butter. Whilst the butter is melting, crack the eggs into a jug and beat them, adding a pinch of salt and pepper. 3. Add the bacon to one side of the pan and let them fry for a couple of minutes on their own. Then add the eggs to the other side of the pan and stir regularly as they scramble. The eggs and bacon should both be done 5 minutes after the eggs are added to the pan. If you find you eggs are done a little before the bacon, remove the scrambled eggs from the pan and place in a bowl. 4. Mix the bacon pieces and scrambled eggs together in a bowl, then spoon into the avocado bowls and get to eatin''!', false, 1),

('CAULIFLOWER CARBONARA SKILLET UNDER 10 CARBS', 'Lunch', '2.5 CUPS OF FROZEN RICED CAULIFLOWER; 8 SLICES BACON; 6 MINCED GARLIC CLOVES; 1 TBSP DRIED ITALIAN HERB SEASONING; 1/2 TSP SALT; 1/2 CUP CASHEW CREAM (1/4 HEAVY CREAM + 1/4 CUP GRATED PARMESAN); 2 EGG YOLKS', '1. Heat a large skillet on medium heat. 2. Use a sharp knife or kitchen shears to cut bacon into 1/2 inch pieces. 3. When the skillet is hot, add the bacon to the skillet. 4. Cook, stirring occasionally until the bacon is mostly crispy, about 6 minutes. 5. Add the minced garlic. 6. Stir well until the garlic begins to brown. 7. Add in the cauliflower rice, salt and dried herbs. 8. Stir well until rice is thawed out and any liquid it released evaporated. 9. Add in the cashew creamer (heavy cream). 10. When it begins to simmer stir until thickened, well combined and creamy. Serve while hot. 11. Top each serving with a fresh egg yolk and mix in. The hot cauliflower risotto with cook the raw yolk. 12. The result is a delicious, creamy dish that everyone will love. 13. No fuss, no grains, no dairy. Garnish with fresh herbs. I love basil on it!', false, 1),

('FLAXSEED CRACKERS', 'Snack', '1 CUP FLAXSEED MEAL; 3 TBSP OLIVE OIL; 1/4 CUP APPLE CIDER VINEGAR; 1-2 TSP WATER; 1/2 TSP SEA SALT', '1. In a bowl mix all of the ingredients. Mix until well combined. Let the mix sit for 20 minutes. 2. Preheat oven on 300F convection bake (or 320F bake). 3. Using a spatula transfer your flaxseed mix to a sheet of parchment paper. 4. Cover with a second sheet and flatten. 5. Use a rolling pin to continue to flatten until you have a square or shape that is about 8x8. 6. Remove the top sheet of parchment paper and move the bottom sheet with dough on it to a baking pan. 7. Pop in the oven and bake for 40-45 minutes until the center is firm, when you tap it it should feel solid. 8. Remove from the oven and let cool to room temp. 9. Transfer the parchment paper with cracker mass on it to a cutting board and with a large kitchen knife cut into squares to break into desired shapes.', false, 1),

('HEALTHY CHICKEN SALAD', 'Lunch', '2 CUPS LEFTOVER SHREDDED CHICKEN BREAST; 2 CUPS CUT, STEAMED GREEN BEANS; 1/2 CUP HOMEMADE MAYO (ONE MINUTE MAYO!); 1/2 CUP CHOPPED PECANS; 1/4 CUP CHOPPED CILANTRO; 1/4 CUP BASIL LEAVES; 1/4 CUP MINT LEAVES; 1/2 TSP SALT; 1/2 TSP WHITE PEPPER', '1. Cut and chop your herbs and pecans. 2. Shred chicken and cut green beans. 3. In a large bowl combine all the ingredients. 4. Toss gently to mix it up. 5. Enjoy, store for quick, healthy meals!', false, 1),

('KETO POKE WITH AHI TUNA AND CITRUS', 'Lunch', '8OZ YELLOW FIN TUNA (AHI TUNA) FILLET; 1 TBSP COCONUT AMINOS; 5 SPRIGS CILANTRO OR ITALIAN PARSLEY (ABOUT 1/4 CUP CHOPPED); 1/2 HAAS AVOCADO; 2 TBSP SESAME OIL; 1 TBSP SESAME SEEDS; 1/4 CUP PILI NUTS; 1 TSP SEA SALT; 1/4 RUBY RED GRAPEFRUIT', '1. Cut your ahi into 1/4 inch cubes and place in a large bowl. 2. Add in the coconut aminos, sesame oil and salt. Gently toss. 3. Halve your grapefruit and cut out the sections, add them to your bowl. 4. Mince your cilantro, add it to the bowl. 5. Chop your pili nuts, dice your avocado, add both to the bowl. 6. Gently toss to combine everything. 7. Divide the ahi mix between two bowls and garnish with sesame seeds. Viola!', false, 1),

('LOW CARB BREAD', 'Snack', '4 ROUNDED TBSP FINE GROUND ALMOND MEAL; 1/4 TSP. BAKING SODA; 1/4 TSP SALT; 1 LARGE EGG; 2 TBSP FAT (MELTED COCONUT OIL, OLIVE OIL, BACON FAT ETC.); 2 TBSP WATER (A SPLASH MORE IF THE MIX SEEMS THICK)', '1. In a small, shallow microwave safe container whisk together the flour, salt and baking soda. 2. Make a well in the center and crack an egg open into it. 3. Whisk well, then add in the fat and water while you continue whisking. 4. Once it becomes frothy start making bigger circles with your whisk or fork to incorporate the flour mix. 5. Mix well, getting all the edges and sides. You can use a spatula to make sure you have it all mixed in. 6. Tap the container down on the counter to settle the mix. 7. Microwave on high for 90 seconds, or until the center is cooked (add cooking time in 30 second intervals). 8. If you''re baking it, use a greased glass dish, and bake at 350F (or 325F convection) for 20 minutes. 9. Run a spatula around the edges to separate and remove it from the container. 10. Pop it in the toaster for 3-4 minutes until crisp. 11. Top with yummy things, enjoy!', false, 1),

('MACADAMIA NUT FATTY TUNA SALAD', 'Lunch', '1-5 OZ CAN SAFE CATCH ALBACORE TUNA; 1 TBSP PRIMAL KITCHEN MAYO (OR ONE MINUTE KETO MAYO); 1 TBSP DIJON MUSTARD (SUGAR FREE); 1/4 CUP HALVED MACADAMIA NUTS; 1 STALK GREEN ONION; 1 TSP SESAME OIL; 9 SLICES CUCUMBER; SALT; PEPPER', '1. Open and drain tuna. Flake tuna into a bowl. 2. Add in the mayo, mustard, sesame oil, salt and pepper. Mix well. 3. Rough chop the macadamia nuts and add them to the bowl. 4. Slice the green onion and add it to the bowl. 5. Mix well. 6. Slice a firm cucumber into 9 thin rounds. Use it to scoop up tuna salad!', false, 1),

('ONE MINUTE KETO MAYO', 'Snack', '3 LARGE EGG YOLKS; 1 TSP MUSTARD; 1 TSP APPLE CIDER VINEGAR; 1/4 TSP SEA SALT; 1/4 TSP. BLACK PEPPER; 1 TSP DRIED HERB BLEND; 1/2 CUP OLIVE OIL', '1. Combine all of the ingredients in a large mason jar or measuring cup. 2. Insert immersion blender (stick blender) and blend until thick and creamy.', false, 1),

('Smoked Salmon Pate with Cucumber', 'Snack', '4.5 oz of smoked salmon; 5.5 oz cream cheese; 1/4 cup of heavy cream; 1 Tbsp. lemon juice; 1 Tbsp. fresh chives; Pinch of salt; PINCH OF pepper; 2 Cucumbers', '1. Begin by using a vegetable peeler or small knife to cut strips down the skin of the cucumbers, and then slice the cucumbers into 2 inch slices. 2. Use a melon baller or a teaspoon, scoop out the flesh in the middle of the cucumber, leaving a small layer at the bottom of each cucumber cup. 3. Next, grab your food processor and add in 3/4 of the smoked salmon, the cream cheese, heavy cream, lemon juice, salt, pepper and chives. Blitz everything for a couple of minutes, until the pâté is smooth. 4. Then, chop up the remaining 1/4 of the smoked salmon into small pieces and add to the pâté. This gives the pâté a little extra texture. 5. Finally, fill each cucumber cup with a dollop of salmon pâté and serve! Alternatively, you can store them in an airtight container in the refrigerator for up to 2 days.', false, 1),

('Bone Broth to Crush Inflammation', 'Lunch', '3 Pastured Chicken Carcasses (or 4 lbs pastured animal bones); 10 cups of filtered water; 2 tbsp. peppercorns; 1 lemon; 3 tsp. turmeric; 1 tsp. salt; 2 tbsp. apple cider vinegar; 3 bay leaves', '1. Pre-heat oven to 400F. Place bones on a sheet pan and sprinkle with salt. Roast for 45 minutes. 2. Next, transfer them to the bowl of your slow cooker (or electric pressure cooker). 3. Add in the peppercorns, bay leaves, apple cider vinegar and water. 4. Cook on low for 24-48 hours. 5. *For pressure cooking, cook on high for 2 hours, then change the pressure cooker function to slow cook and cook on low for 12 hours. 6. When done, place a fine mesh sieve or strainer over a large bowl or pitcher. Carefully strain broth. 7. Discard the bones, bay leaves and peppercorns. 8. Distribute the broth between three mason jars, about 2 cups each. 9. Mix in 1 tsp of turmeric to each jar and add 1-2 slices of lemon. 10. Store in the fridge for up to 5 days. 11. To heat, gently simmer stove top with a lemon slice.', false, 1),

('Spring Keto Stew with Venison', 'Dinner', '1lb stew meat, venison; 2 tbsp. olive oil or butter; 1 bulb elephant garlic; 1 cup shredded purple cabbage; 1 cup sliced celery; 1 tsp. salt; 1 tsp. pepper; 4 cups bone broth; 2 cups chopped thin asparagus; 2 bay leaves', '1. Peel the elephant garlic and slice into 1/8 inch thin slices. 2. Slice the cabbage and the celery. 3. In a large skillet heat the olive oil or butter. 4. Add in the garlic, celery, bay leaves and cabbage. Sauté until tender, about 6 minutes. 5. Add in the venison, salt and pepper. Stir until the meat is browned. 6. Transfer everything to a slow cooker. 7. Add in the bone broth and set to cook on low for 6 hours. 8. When done, add in the chopped up asparagus and stir well. 9. Serve with a healthy olive oil drizzle and lime!', false, 1),

('Tom Yum Kung (Thai Seafood Soup)', 'Dinner', '1/4 cup olive oil; 4 cups bone broth; 1 cup coconut milk; 2 lbs white fish filet (no scales or bones); 2 bay leaves; 1 large vidalia onion; 4 garlic cloves; 3 carrots; 2 tsp. salt; 4 baby bok choy; 2 cans water chestnuts; 3 lemons; 1 bunch cilantro; 2 tbsp. wasabi powder; 2 tbsp. fish sauce (to taste)', '1. In a large stock pot heat 2 tbsp of fat on medium heat. 2. Small dice garlic, ginger, onions and carrots. 3. Once the pot is heated add the diced veggies to the pot with the bay leaf. 4. Cook stirring occasionally until tender, about 8 minutes. 5. In the meantime cut your fish into 1-inch pieces and cut, wash and pull apart your bok choy. 6. Peel a few strips of lemon rind off of your lemons, add them to the pot. 7. Add the fish into the pot and stir well, until all the fish is seared. 8. Add in the salt and the cashew cream, fish sauce and wasabi powder. Mix well. 9. Add in the broth, bring to a boil, let it boil for 10 minutes. 10. Add in the bok choy, water chestnuts. Stir. Bring to a simmer. 11. Juice all your lemons. Set aside. 12. Let the soup simmer for another 10 minutes. 13. Dice your cilantro. 14. Add in the lemon juice. Stir. Taste, adjust salt and needed. If you want it thinner, add in a cup of water. 15. Serve with plenty of fresh cilantro and drizzle remaining olive oil on top.', false, 1),

('Easy Ketogenic Breakfast Tacos', 'Breakfast', '3 oz aged cheddar (Tilamook); 1 large pastured egg; 2 slices pastured, sugar free bacon; 2 sprigs cilantro; Handful of arugula; 1 tsp. ghee; Pinch of salt; Pinch of pepper; Pinch of turmeric', '1. Cook bacon first, you can pan fry it or pop it in the oven at 350F until crispy. Set aside. 2. Shred your cheese with a cheese grater. 3. Heat skillet on medium high heat. Once it''s come to temperature add the ghee into the skillet. 4. Sprinkle the cheese into the skillet in a circle. 5. It will begin to melt almost instantly. Once all of the cheese is melted and bubbling, crack the egg into the center of your cheese circle. Sprinkle the yolk with salt, pepper and turmeric. 6. Cook here for 2 minutes until the egg begins to become opaque and the cheese begins to brown. 7. Cover with a tight fitting lid and lower the heat. Cook covered for 2 minutes. 8. Remove from heat, the egg should be fully cooked and the cheese crispy. 9. Carefully slide your cheese egg onto a cutting board or dish. Use two bowls or cups, or even the cheese grater to hold up the sides of the sheet taco so that as the shell cools and hardens the sides stay up. 10. Add in your bacon, arugula and cilantro. 11. Grab your shell and dig in. Eat over a plate because you don''t want your yolk to run all over the floor!', false, 1),

('The Keto Almond Butter Burger', 'Dinner', '2 lbs ground turkey; 1 tsp. apple cider vinegar; 1 large egg; 1/2 cup almond butter, crunchy unsweetened; 1 tsp. garlic salt; 1/2 tsp. onion salt; 1 tsp. black pepper; 1 tsp. turmeric; 1 tbsp. fish sauce', '1. Pre-heat oven to 400F. 2. Mix everything in a large bowl until thoroughly and evenly combined. 3. Lightly grease a large baking sheet. 4. Shape 10 patties, about 4 ounces each. Place on the baking sheet. 5. Bake for 20-25 minutes.', false, 1),

('Keto Power Breakfast with Green Sauce', 'Breakfast', '1 cup baby spinach (baby kale); 1 cup arugula; 1 cup parsley (or cilantro or basil etc.); 5 medium garlic cloves; 5 tbsp. of hemp hearts; 1 cup olive oil; 5 slices bacon; 2 eggs; 20 asparagus tips; Salt to taste ; pepper to taste', '1. Green Sauce: Combine baby spinach, arugula, parsley, garlic cloves, hemp hearts and olive oil in a blender or food processor and blend on low until well combined and almost smooth. Set aside. 2. On a sheet pan arrange your bacon slices into rings, arrange the rings in a circle. 3. Pop the sheet pan in the oven and set it to 350F. When the oven comes to temperature, remove the sheet pan from the oven (don''t turn it off). Tuck 4 asparagus tips into each bacon ring. 4. Move your bacon rings closer together if needed, and then crack two eggs in between them. 5. Add your green sauce, sprinkle a little salt and pepper and pop back in the oven for 20 minutes. 6. Remove from the oven, and dig in! No need for plates. Makes enough for two!', false, 1),

('Tuna Zoodle Casserole', 'Dinner', '1 large zucchini; 2 cans Safe Catch Albacore Tuna, in water; 1/2 cup diced onion; 1 minced garlic clove; 3 large cremini mushrooms; 1 tsp. mustard; 1 tsp. salt; 1 tsp. black pepper; 1/2 tsp. dried rosemary; 1 tbsp. lemon juice; 2-3 tbsp. mayo (We love primal kitchen or homemade); 1 broccoli crown; 1/2 cup chopped pecans; 2/3 cup cashew cream*', '1. First, make sure you have your mayo and cashew cream ready!  2. Pre-heat your oven to 325F. 3. Zoodle your zucchini. Lay the zoodles flat on a clean kitchen towel and sprinkle with salt. Let them rest here to they release liquid while you prep the rest. 4. Mince onion and garlic, add in to the casserole dish. 5. Thinly slice mushrooms and add them to the dish too. 6. Open and drain tuna cans, flake the tuna into the casserole dish. 7. Add in the salt, pepper, 1 tbsp mayo, mustard, lemon juice and rosemary. 8. Mix well. 9. Wrap the kitchen towel around the zucchini and squeeze the water out. 10. Add the zoodles to the casserole dish and toss to combine. 11. Pour in the cashew cream. Gently Mix. 12. Cut your broccoli crown into florets and mince them into 1/4 inch pieces. 13. Toss with chopped pecans in a bowl and mix with remaining mayo. 14. Spread this mix over the top of the casserole. 15. Sprinkle lightly with salt. 16. Place in the oven and bake for 30-35 minutes. 17. It will be toasty on top and creamy inside! Make sure to use a knife to cut your pieces before serving or your zoodles will pull out the whole thing!', false, 1),

('Chocolate Chip Keto Cookie', 'Dessert', '1 egg; 3 tbsp. melted coconut oil (or macadamia nut oil); 1/3 cup Swerve granulated sweetener; 1/3 cup milk (nut milk, coconut milk); 1 tsp. vanilla extract; 2 cups fine ground almond meal; 1/2 tsp. baking soda; 1 tsp. coarse sea salt; 2 bars of dark chocolate', '1. In a medium bowl, whisk egg until frothy. 2. Keep whisking as you add in the oil, vanilla and sweetener. 3. Mix well. 4. Add in the baking soda, salt, collagen peptides and almond meal. 5. Mix with a spatula until the dough is crumbly. 6. Add in the milk, mix in. 7. Once the dough is moist, chop the chocolate into small pieces and fold in. 8. Shape 1 inch balls with the dough, set on a plate, cover and pop them in the fridge for 30 - 60 min. 9. Pre-heat oven to 325F convection (or 350F bake). 10. Place cookie dough balls on sheet pan (greased or lined with parchment paper). 11. Gently and lightly flatten the dough balls. 12. Bake 15-18 minutes until the base of the cookies turn golden brown. 13. Remove from oven, let cool for ten minutes (if you can stand to wait to eat these!)', false, 1),

('Low-Carb Acai Almond Butter Smoothie', 'Breakfast', '1 100g Pack Unsweetened Acai Puree; 3/4 cup Unsweetened Almond Milk; 1/4 of an Avocado; 3 tbsp. Collagen or Protein Powder; 1 tbsp. Coconut Oil or MCT Oil Powder; 1 tbsp. Almond Butter; 1/2 tsp. Vanilla Extract; 2 drops Liquid Stevia (optional)', '1. If you are using individualized 100 gram packs of acai puree, run the pack under lukewarm water for a few seconds until you are able to break up the puree into smaller pieces. Open the pack and put the contents into the blender. 2. Place the remaining ingredients in the blender and blend until smooth. 3. Add more water or ice cubes as needed. Drizzle the almond butter along the side of the glass to make it look cool. 4. Enjoy and pat yourself on the back for an awesome workout and killer post workout smoothie!', false, 1),

('Low Carb Lemon Cashew Cookies', 'Dessert', '1 cup Cashew Butter; 2 Eggs; Zest of 1 Lemon; Juice of 1 Lemon; 1/2 tsp. Vanilla Extract; 6-10 drops Liquid Stevia (about 1/4 tsp. powdered stevia); 1/4 tsp. Baking Soda', '1. Preheat the oven to 350°. 2. Wash the lemon and dry it thoroughly. Use a fine grater to zest the lemon rind into a large bowl. Be sure to get the entire colorful outer layer of the lemon. Then cut open the lemon and squeeze the juice into the bowl being careful not to let any seeds in the bowl. 3. Add the cashew butter, eggs, vanilla, baking soda and stevia to the bowl and mix with a fork or spoon until all of the ingredients are fully blended. 4. The consistency will be like a thick viscous batter which is a bit thicker than nut butter, but a bit thinner than usual cookie dough. Take 12 small heaps of the batter and place onto a cookie sheet shaping into a cookie shape. 5. Bake at 350° for about 10-15 minutes. Let cool before serving.', false, 1),

('Macadamia Nut Fat Bomb', 'Dessert', '1/3 cup unrefined coconut oil (room temp); 2 tbsp. unsweetened cocoa powder; 2 tbsp. erythritol or Swerve; 1 tsp. vanilla extract; 12 macadamia nuts; Pinch salt', '1. In a small bowl whisk together the coconut oil, vanilla, sweetener and vanilla extract until smooth. 2. Line a small container with parchment paper. Pour in the chocolate mix, use a spatula to spread it thin and evenly along the bottom. I recommend a container no bigger than 4x6. 3. Place macadamia nuts in chocolate mix. You can be really systematic about it or make fun shapes. Sprinkle salt lightly all over. 4. Place the container in the freezer for 20 minutes. Remove, cut into 6 even squares. 5. Store in the freezer for a quick sweet treat or fat bomb.', false, 1);